version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: 'deps:'
    reviewers:
      - adamledwards
      - jpveooys

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ci
    commit-message:
      prefix: 'ci:'
    reviewers:
      - adamledwards
      - jpveooys
