version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: 'deps:'
      prefix-development: 'deps-dev:'
    groups:
      babel:
        patterns:
          - '@babel/*'
      commitlint:
        patterns:
          - '@commitlint/*'
      testing-library:
        patterns:
          - '@testing-library/*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ci
    commit-message:
      prefix: 'ci:'
