repos:
  - repo: local
    hooks:
      - id: mod-gitleaks
        name: Gitleaks
        description: This hook scans for secrets
        entry: gitleaks detect -c gitleaks.toml -s . --no-git --verbose
        language: golang
