name: Bug report
description: Report a bug or regression
labels:
  - bug
  - awaiting triage
body:
  - type: markdown
    attributes:
      value: |
        You’re reporting a bug in MOD.UK Frontend. All questions are optional – fill in as much of the form as you’re able to.

        All issues created in this repository are public. Do not include any sensitive information.
  - type: textarea
    id: repro-steps
    attributes:
      label: What steps will reproduce the bug?
      description: Include a code snippet or public link if relevant
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
  - type: textarea
    id: actual
    attributes:
      label: What happened instead?
      description: Attach a screenshot or screen recording if relevant
  - type: input
    id: version
    attributes:
      label: What version of MOD.UK Frontend were you using?
      description: The version of the @moduk/frontend package the problem was seen in
  - type: textarea
    id: browser-os
    attributes:
      label: What web browsers and operating systems were you using?
      description: For example, Firefox 108 on Windows 10 and Chrome 105 on Android 13
  - type: textarea
    id: additional-info
    attributes:
      label: Context and anything else
      description: What are you trying to accomplish? How has this issue affected you? Do you have a suggested fix?
