name: Set up Node.js and install dependencies
description: Sets up Node.js and installs dependencies
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        cache: npm
        node-version-file: .nvmrc
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: npm ci
