name: Set up Node.js and install dependencies
description: Sets up Node.js and installs dependencies
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci
