name: Merge sharded Playwright blob reports
description: Merges sharded Playwright blob reports
inputs:
  input-artifact:
    required: true
    description: Name of the artefact containing blob reports
  output-artifact:
    required: true
    description: Name of the artefact to save the HTML report as
runs:
  using: composite
  steps:
    - name: Download blob reports
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
        # v4 of upload-artifact does not allow uploading to the same artifact multiple times, so have to enumerate each artifact
        # See https://github.com/actions/upload-artifact/issues/480
        name: ${{ inputs.input-artifact }}-${{ strategy.job-index }}
        path: blob-reports

    - name: Merge reports
      shell: bash
      run: npm exec --no -- playwright merge-reports --reporter html blob-reports

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        # v4 of upload-artifact does not allow uploading to the same artifact multiple times, so have to enumerate each artifact
        # See https://github.com/actions/upload-artifact/issues/480
        name: ${{ inputs.output-artifact }}-${{ strategy.job-index }}
        path: playwright-report
